name: Build FreeBsd Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'input_tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build FreeBsd
    steps:
    - uses: actions/checkout@v4
    - name: Build Release
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        release: 13.2
        prepare: |
          pkg install -y node wget curl git bash gawk gsed python
          source /usr/local/etc/profile.d/paths.sh
        run: |
          ls 
          pip install pyinstaller
          pyinstaller --onefile --name=gpt4api --distpath=. app.py

    - name: Generate release tag
      id: tag
      run: echo "release_tag=${{ github.event.inputs.name }}" >> $GITHUB_OUTPUT

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUP_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
              gpt4api
              
